<?php
function repositoryagentsearch_search_info(){
    return array(
    'title' => 'Agents',
    'path' => 'agents',
    'conditions_callback' => 'repository_callback_search_conditions',
  );
}
function repositoryagentsearch_form_search_form_alter(&$form, &$form_state) {
  if (isset($form['module']) && $form['module']['#value'] == 'repositoryagentsearch' && user_access('use advanced search')) {
    $form['advanced'] = array(
      '#type' => 'fieldset',
      '#title' => t('Advanced search'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#attributes' => array('class' => array('search-advanced')),
    );

    $form['advanced']['agentType'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Only of type(s)'),
      '#options' => drupal_map_assoc(array("Person","Organisation","Group"))
    );
    $form['advanced']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Advanced search'),
      '#weight' => 100,
    );
    //$form['advanced']['#validate'][] = 'search_form_validate';
    //$form['advanced']['#validate'][] = 'repositoryagentsearch_search_form_validate';
    $form['#validate'][] = 'repositoryagentsearch_search_form_validate';
  }
}/**
 * Form validation handler for repositoryagentsearch_form_search_form_alter().
 */
function repositoryagentsearch_search_form_validate($form, &$form_state) {
  // Initialize using any existing basic search keywords.
  $keys = $form_state['values']['processed_keys'];
  // Insert extra restrictions into the search keywords string.
  if (isset($form_state['values']['agentType']) && is_array($form_state['values']['agentType'])) {
    // Retrieve selected types - Form API sets the value of unselected
    // checkboxes to 0.
    $form_state['values']['agentType'] = array_filter($form_state['values']['agentType']);
    if (count($form_state['values']['agentType'])) {
      $keys = search_expression_insert($keys, 'agentType', implode(',', array_keys($form_state['values']['agentType'])));
    }
  }
  if (!empty($keys)) {
    form_set_value($form['basic']['processed_keys'], trim($keys), $form_state);
  }
}

function repositoryagentsearch_search_execute($keys = NULL, $conditions = NULL){
    //var_dump($keys);
    //var_dump($conditions);
    $project = null;
    if (ISSET($conditions['project'])){
        $project = $conditions['project'];
    }
    $searchResults = _findRecords("agents",array("lastName","firstName"),100, 0, 1, $keys,null,$project);
    $results = array();
    foreach ($searchResults as $obj){
      $numrev = count($obj['_revisions']) - 1;

      $id = $obj['_id'];
      $metadata = $obj['_revisions'][$numrev];
      // generate uri
      $uri = 'repository/agents/' . $id->{'$id'};
      $snippet = "";
      if (ISSET($metadata['biography'])){
          $snippet = text_summary($metadata['biography']);
      }
      $results [] = array(
        'link' => url($uri, array('absolute' => TRUE)),
          'type' => 'Agent',
          'title' => $metadata['lastName'] . ", " . $metadata['firstName'],
          'user' => "",
          'date' => "",
          'extra' => null,
          'snippet' => $snippet
        );
     }
    return $results;
}