<?php
function repositoryartefactsearch_search_info(){
    return array(
    'title' => 'Artefacts',
    'path' => 'artefacts',
    'conditions_callback' => 'repository_callback_search_conditions',
  );
}
function repositoryartefactsearch_search_execute($keys = NULL, $conditions = NULL){
    if (ISSET($conditions['project'])){
        $project = $conditions['project'];
    }
    if (!$keys) {
      return;
    }

    $query = new AusteseElasticSearchQuery();
    $query->project = $project;
    $query->type = "artefacts";

    $results = $query->search($keys);

    return $results;
}
