<?php
function repositoryversionsearch_search_info(){
    return array(
    'title' => 'Versions',
    'path' => 'versions',
    'conditions_callback' => 'repository_callback_search_conditions',
  );
}


function repositoryversionsearch_search_execute($keys = NULL, $conditions = NULL) {
    if (ISSET($conditions['project'])){
        $project = $conditions['project'];
    }
    if (!$keys) {
      return;
    }

    $query = new AusteseElasticSearchQuery();
    $query->project = $project;
    $query->type = 'versions';

    $results = $query->search($keys);

    return $results;
}
