Ext.define('austese_repository.form.MultiFileFieldButton', {
    extend: 'Ext.button.Button',
    alias: 'widget.multifilefieldbutton',
    renderTpl: [
                '<em id="{id}-btnWrap"<tpl if="splitCls"> class="{splitCls}"</tpl>>',
                    '<tpl if="href">',
                        '<a id="{id}-btnEl" href="{href}" class="{btnCls}" target="{hrefTarget}"',
                            '<tpl if="tabIndex"> tabIndex="{tabIndex}"</tpl>',
                            '<tpl if="disabled"> disabled="disabled"</tpl>',
                            ' role="link">',
                            '<span id="{id}-btnInnerEl" class="{baseCls}-inner">',
                                '{text}',
                            '</span>',
                            '<span id="{id}-btnIconEl" class="{baseCls}-icon {iconCls}"<tpl if="iconUrl"> style="background-image:url({iconUrl})"</tpl>><input type="file" name="data" multiple="multiple"></span>',
                        '</a>',
                    '<tpl else>',
                        '<button id="{id}-btnEl" type="{type}" class="{btnCls}" hidefocus="true"',
                            '<tpl if="tabIndex"> tabIndex="{tabIndex}"</tpl>',
                            '<tpl if="disabled"> disabled="disabled"</tpl>',
                            ' role="button" autocomplete="off">',
                            '<span id="{id}-btnInnerEl" class="{baseCls}-inner" style="{innerSpanStyle}">',
                                '{text}',
                            '</span>',
                            '<span id="{id}-btnIconEl" class="{baseCls}-icon {iconCls}"<tpl if="iconUrl"> style="background-image:url({iconUrl})"</tpl>><input type="file" name="data" multiple="multiple"></span>',
                        '</button>',
                    '</tpl>',
                '</em>'
            ],
});